# permissions for end users to edit dhcpleases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: test
    app.kubernetes.io/managed-by: kustomize
  name: dhcpleases-editor-role
rules:
- apiGroups:
  - dhcp.lootbot.cloud
  resources:
  - dhcpleases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dhcp.lootbot.cloud
  resources:
  - dhcpleases/status
  verbs:
  - get
