# permissions for end users to view dhcpsubnets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: test
    app.kubernetes.io/managed-by: kustomize
  name: dhcpsubnet-viewer-role
rules:
- apiGroups:
  - dhcp.lootbot.cloud
  resources:
  - dhcpsubnets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dhcp.lootbot.cloud
  resources:
  - dhcpsubnets/status
  verbs:
  - get
