# permissions for end users to edit dhcpservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: test
    app.kubernetes.io/managed-by: kustomize
  name: dhcpserver-editor-role
rules:
- apiGroups:
  - dhcp.lootbot.cloud
  resources:
  - dhcpservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dhcp.lootbot.cloud
  resources:
  - dhcpservers/status
  verbs:
  - get
