apiVersion: dhcp.lootbot.cloud/v1
kind: DHCPServer
metadata:
  labels:
    app.kubernetes.io/name: test
    app.kubernetes.io/managed-by: kustomize
  name: dhcpserver-sample
  namespace: default
spec:
  listenAddress: "0.0.0.0"
  listenInterface: "ens0"
  reuseAddr: true